Qc\QcBeDomainColor\Event\ItemsProcFunc:
  public: true
  tags:
    - name: event.listener
      identifier: 'items-proc-func'
      event: \TYPO3\CMS\Backend\Controller\Event\AfterBackendPageRenderEvent
