services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Qc\QcBeDomainColor\:
    resource: '../Classes/*'

  Qc\QcBeDomainColor\Events\ItemsProcFunc:
    public: true
    tags:
      - name: event.listener
        identifier: 'qc-be-domain-color/backend/after-backend-page-render'

